'use strict';

const operations = require('../../core/operations');

const CAPABILITIES = Object.freeze([
  'ordered_steps', 'verifier', 'evidence_states', 'failure_status',
  'cancellation_status', 'receipt_path',
]);

const STEP_RUNNER = "const{spawnSync}=require('child_process');const a=JSON.parse(Buffer.from(process.env.CITADEL_ARGV_B64,'base64').toString('utf8'));const r=spawnSync(a[0],a.slice(1),{stdio:'inherit',shell:false});process.exit(r.error?127:(r.status??1))";
const SEMANTIC_GUARD = "const s=JSON.parse(Buffer.from(process.env.CITADEL_SEMANTIC_CONTRACT_B64,'base64').toString('utf8'));const ok=s.evidence.states.join(',')==='passed,failed,blocked,unknown'&&s.evidence.required_status==='passed'&&s.evidence.missing_status==='unknown'&&s.outcomes.success==='passed'&&s.outcomes.failure==='failed'&&s.outcomes.cancellation==='unknown'&&s.receipt.required_for_pass===true&&s.receipt.missing_status==='unknown';if(!ok)throw new Error('Citadel semantic contract rejected')";

function encode(value) {
  return Buffer.from(operations.canonicalSerialize(value), 'utf8').toString('base64');
}

function decode(value) {
  return JSON.parse(Buffer.from(value, 'base64').toString('utf8'));
}

function yamlScalar(value) {
  return JSON.stringify(String(value));
}

function compile({ workflow, core, semantics }) {
  const coreB64 = encode(core);
  const semanticsB64 = encode(semantics);
  const lines = [
    '# Generated by Citadel workflow compiler. Do not edit by hand.',
    `# Citadel core contract b64: ${coreB64}`,
    `# Citadel semantic contract b64: ${semanticsB64}`,
    `name: ${yamlScalar(`Citadel ${core.operation_id}`)}`,
    '',
    'on:',
    '  pull_request:',
    '  push:',
    '    branches: [main]',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  verify-change:',
    '    runs-on: ubuntu-latest',
    '    env:',
    `      CITADEL_CORE_CONTRACT_B64: ${yamlScalar(coreB64)}`,
    `      CITADEL_SEMANTIC_CONTRACT_B64: ${yamlScalar(semanticsB64)}`,
    `      CITADEL_OPERATION_ID: ${yamlScalar(core.operation_id)}`,
    `      CITADEL_OPERATION_DIGEST: ${yamlScalar(core.operation_digest)}`,
    `      CITADEL_WORKFLOW_DIGEST: ${yamlScalar(core.workflow_digest)}`,
    `      CITADEL_EVIDENCE_STATES: ${yamlScalar(core.evidence_states.join(','))}`,
    `      CITADEL_FAILURE_STATUS: ${yamlScalar(core.failure_status)}`,
    `      CITADEL_CANCELLATION_STATUS: ${yamlScalar(core.cancellation_status)}`,
    `      CITADEL_RECEIPT_PATH: ${yamlScalar(core.receipt_path)}`,
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0',
    '      - name: Verify Citadel semantic contract',
    '        id: citadel-semantic-contract',
    '        shell: bash',
    `        run: node -e ${yamlScalar(SEMANTIC_GUARD)}`,
  ];
  workflow.steps.forEach((step, index) => {
    const verifier = step.id === workflow.verifier.step_id;
    lines.push(
      `      - name: ${yamlScalar(`Citadel step ${index + 1}`)}`,
      `        id: citadel-step-${String(index + 1).padStart(3, '0')}`,
      '        shell: bash',
      '        env:',
      `          CITADEL_STEP_ID_B64: ${yamlScalar(encode(step.id))}`,
      `          CITADEL_ARGV_B64: ${yamlScalar(encode(step.argv))}`,
      `          CITADEL_EVIDENCE_TYPE: ${yamlScalar(step.evidence_type)}`,
      `          CITADEL_VERIFIER: ${yamlScalar(verifier ? 'true' : 'false')}`,
      `          CITADEL_REQUIRED_STATUS: ${yamlScalar(verifier ? workflow.verifier.required_status : '')}`,
      `          CITADEL_MISSING_EVIDENCE_STATUS: ${yamlScalar(verifier ? workflow.verifier.missing_evidence_status : '')}`,
      `        run: node -e ${yamlScalar(STEP_RUNNER)}`,
    );
  });
  return {
    output_path: `.github/workflows/${workflow.operation.operation_id}.yml`,
    media_type: 'application/yaml',
    content: `${lines.join('\n')}\n`,
  };
}

function header(content, name) {
  const match = content.match(new RegExp(`^# Citadel ${name} b64: ([A-Za-z0-9+/=]+)$`, 'm'));
  if (!match) throw new Error(`GitHub artifact is missing ${name}`);
  return decode(match[1]);
}

function environmentValue(content, name) {
  const match = content.match(new RegExp(`^\\s+${name}: ("[^"\\r\\n]*")$`, 'm'));
  if (!match) throw new Error(`GitHub artifact is missing ${name}`);
  return JSON.parse(match[1]);
}

function inspect(content) {
  if (content.includes('${{')) throw new Error('GitHub artifact contains an expression interpolation');
  const core = header(content, 'core contract');
  const declaredSemantics = header(content, 'semantic contract');
  const stepPattern = /id: citadel-step-\d{3}\n\s+shell: bash\n\s+env:\n\s+CITADEL_STEP_ID_B64: "([A-Za-z0-9+/=]+)"\n\s+CITADEL_ARGV_B64: "([A-Za-z0-9+/=]+)"\n\s+CITADEL_EVIDENCE_TYPE: "([^"]+)"\n\s+CITADEL_VERIFIER: "(true|false)"\n\s+CITADEL_REQUIRED_STATUS: "([^"]*)"\n\s+CITADEL_MISSING_EVIDENCE_STATUS: "([^"]*)"\n\s+run: node -e "([^"]+)"/g;
  const steps = [];
  let verifier = null;
  for (const match of content.matchAll(stepPattern)) {
    if (match[7] !== STEP_RUNNER) throw new Error('GitHub artifact step runner was modified');
    const step = { id: decode(match[1]), argv: decode(match[2]), evidence_type: match[3] };
    steps.push(step);
    if (match[4] === 'true') {
      if (verifier) throw new Error('GitHub artifact has multiple verifier steps');
      verifier = { step_id: step.id, required_status: match[5], missing_evidence_status: match[6] };
    }
  }
  if (steps.length === 0) throw new Error('GitHub artifact has no executable steps');
  const stepIds = steps.map((step) => step.id);
  const stepCommandsDigest = operations.sha256Digest(steps.map((step) => ({ id: step.id, argv: step.argv })));
  const semantics = {
    schema_version: 1,
    operation_id: environmentValue(content, 'CITADEL_OPERATION_ID'),
    step_ids: stepIds,
    step_commands_digest: stepCommandsDigest,
    verifier,
    evidence: {
      states: environmentValue(content, 'CITADEL_EVIDENCE_STATES').split(','),
      required_status: verifier?.required_status,
      missing_status: verifier?.missing_evidence_status,
    },
    outcomes: {
      success: verifier?.required_status,
      failure: environmentValue(content, 'CITADEL_FAILURE_STATUS'),
      cancellation: environmentValue(content, 'CITADEL_CANCELLATION_STATUS'),
    },
    receipt: {
      path: environmentValue(content, 'CITADEL_RECEIPT_PATH'),
      required_for_pass: declaredSemantics.receipt?.required_for_pass,
      missing_status: verifier?.missing_evidence_status,
    },
  };
  const guardRun = `run: node -e ${yamlScalar(SEMANTIC_GUARD)}`;
  const runtimeCore = decode(environmentValue(content, 'CITADEL_CORE_CONTRACT_B64'));
  const runtimeSemantics = decode(environmentValue(content, 'CITADEL_SEMANTIC_CONTRACT_B64'));
  return {
    core_contract: core,
    semantic_contract: semantics,
    step_ids: stepIds,
    step_commands_digest: stepCommandsDigest,
    verifier,
    executable_guard: content.includes('id: citadel-semantic-contract') && content.includes(guardRun)
      && operations.canonicalSerialize(runtimeCore) === operations.canonicalSerialize(core)
      && operations.canonicalSerialize(runtimeSemantics) === operations.canonicalSerialize(declaredSemantics),
    artifact_digest: operations.sha256Digest({ media_type: 'application/yaml', content }),
  };
}

module.exports = Object.freeze({
  id: 'github-actions', capabilities: CAPABILITIES, compile, decode, encode, inspect, yamlScalar,
});
