#!/usr/bin/env node

/**
 * codex-compat.js -- Generates all Codex CLI artifacts from Citadel source.
 *
 * Reads Citadel's skills, agents, hooks, MCP config, and package.json,
 * then generates Codex-native equivalents:
 *
 *   .codex/config.toml                     Required feature flags and agent config
 *   .codex-plugin/plugin.json              Plugin manifest for Codex marketplace
 *   .codex/agents/{name}.toml              Translated agent definitions
 *   .agents/skills/{name}/SKILL.md         Skill copies for Codex discovery
 *   .agents/skills/{name}/agents/openai.yaml   UI metadata per skill
 *
 * Usage:
 *   node scripts/codex-compat.js                    # from project root
 *   node scripts/codex-compat.js /path/to/project   # explicit project path
 *   node scripts/codex-compat.js --dry-run           # show what would be generated
 *
 * Generated files include headers marking them as Citadel-managed.
 * Re-running is idempotent -- overwrites generated files, never touches hand-authored ones.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const CITADEL_ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const PROJECT_ROOT = args.find(a => !a.startsWith('--')) || process.env.CLAUDE_PROJECT_DIR || process.cwd();

// ---- Utility helpers --------------------------------------------------------

function ensureDir(dir) {
  if (!DRY_RUN && !fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function writeFile(filePath, content) {
  if (DRY_RUN) {
    console.log(`  [dry-run] Would write: ${filePath}`);
    return;
  }
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
}

function readJSON(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    return null;
  }
}

function parseFrontmatter(content) {
  // Normalize line endings to \n for consistent parsing
  const normalized = content.replace(/\r\n/g, '\n');
  const match = normalized.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split('\n')) {
    // Skip YAML list items (lines starting with -)
    if (line.trim().startsWith('-')) continue;
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    // Skip indented keys (nested YAML)
    if (line.match(/^\s+\w/)) continue;
    let val = line.slice(colonIdx + 1).trim();
    // Strip YAML quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    // Handle multiline description (>-)
    if (val === '>-' || val === '>') {
      continue;
    }
    if (key && val) fm[key] = val;
  }
  // Handle multiline description by regex
  const descMatch = normalized.match(/description:\s*>-?\n([\s\S]*?)(?=\n[a-zA-Z][\w-]*:|\n---)/);
  if (descMatch) {
    fm.description = descMatch[1].replace(/\n\s*/g, ' ').trim();
  }
  return fm;
}

// ---- 1. Generate .codex/config.toml -----------------------------------------

function generateConfigToml() {
  console.log('Generating .codex/config.toml...');

  // Read .mcp.json for MCP server entries
  let mcpSection = '';
  const mcpPath = path.join(PROJECT_ROOT, '.mcp.json');
  const mcpData = readJSON(mcpPath);
  if (mcpData && mcpData.mcpServers) {
    const entries = [];
    for (const [name, config] of Object.entries(mcpData.mcpServers)) {
      // Skip comments and disabled entries (prefixed with _)
      if (name.startsWith('_')) continue;
      entries.push(mcpServerToToml(name, config));
    }
    if (entries.length > 0) {
      mcpSection = '\n' + entries.join('\n');
    }
  }

  const toml = `# Generated by Citadel. Do not edit manually.
# Re-generate with: node ${CITADEL_ROOT.replace(/\\/g, '/')}/scripts/codex-compat.js

# Required feature flags for Citadel harness
[features]
codex_hooks = true
multi_agent = true
skill_mcp_dependency_install = true

# Agent configuration
[agents]
max_depth = 1
max_threads = 6
job_max_runtime_seconds = 1800

# Session persistence
[history]
persistence = "save-all"

# Shell environment
[shell_environment_policy]
inherit = "core"
set = { CITADEL_RUNTIME = "codex" }
exclude = ["*SECRET*", "*TOKEN*", "*KEY*"]
${mcpSection}
`;

  writeFile(path.join(PROJECT_ROOT, '.codex', 'config.toml'), toml);
}

function mcpServerToToml(name, config) {
  let lines = [`[mcp_servers.${name}]`];

  if (config.command) {
    lines.push(`command = "${config.command}"`);
  }
  if (config.args && config.args.length > 0) {
    const argsStr = config.args.map(a => `"${a}"`).join(', ');
    lines.push(`args = [${argsStr}]`);
  }
  if (config.url) {
    lines.push(`url = "${config.url}"`);
  }
  if (config.env) {
    for (const [k, v] of Object.entries(config.env)) {
      if (k.startsWith('_')) continue;
      // Map env vars to bearer_token_env_var if it looks like a token
      if (k.toLowerCase().includes('token')) {
        lines.push(`bearer_token_env_var = "${k}"`);
      }
    }
  }
  lines.push('');
  return lines.join('\n');
}

// ---- 2. Generate .codex-plugin/plugin.json ----------------------------------

function generatePluginManifest() {
  console.log('Generating .codex-plugin/plugin.json...');

  const pkg = readJSON(path.join(CITADEL_ROOT, 'package.json')) || {};
  const repoUrl = (pkg.repository && pkg.repository.url) || '';

  // Count skills
  const skillsDir = path.join(CITADEL_ROOT, 'skills');
  let skillCount = 0;
  if (fs.existsSync(skillsDir)) {
    skillCount = fs.readdirSync(skillsDir).filter(d =>
      fs.existsSync(path.join(skillsDir, d, 'SKILL.md'))
    ).length;
  }

  const manifest = {
    name: pkg.name || 'citadel',
    version: pkg.version || '1.0.0',
    description: pkg.description || 'Agent orchestration harness',
    author: {
      name: pkg.author || 'Citadel',
      url: repoUrl.replace(/\.git$/, ''),
    },
    license: pkg.license || 'MIT',
    keywords: pkg.keywords || ['orchestration', 'campaigns', 'fleet'],
    skills: './skills/',
    interface: {
      displayName: 'Citadel Harness',
      shortDescription: `Agent orchestration: ${skillCount} skills, campaigns, fleet coordination, quality gates`,
      category: 'Developer Tools',
      capabilities: [
        'orchestration',
        'campaigns',
        'parallel-agents',
        'quality-gates',
        'telemetry',
        'intent-routing',
      ],
    },
  };

  // Add mcpServers pointer if .mcp.json exists
  if (fs.existsSync(path.join(PROJECT_ROOT, '.mcp.json'))) {
    manifest.mcpServers = './.mcp.json';
  }

  const content = '// Generated by Citadel. Do not edit manually.\n'
    + JSON.stringify(manifest, null, 2) + '\n';

  writeFile(path.join(PROJECT_ROOT, '.codex-plugin', 'plugin.json'), content);
}

// ---- 3. Translate agent definitions -----------------------------------------

function translateAgents() {
  console.log('Translating agent definitions...');

  const agentsDir = path.join(CITADEL_ROOT, 'agents');
  if (!fs.existsSync(agentsDir)) {
    console.log('  No agents/ directory found, skipping.');
    return;
  }

  const agentFiles = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));

  for (const file of agentFiles) {
    const content = fs.readFileSync(path.join(agentsDir, file), 'utf8');
    const fm = parseFrontmatter(content);
    if (!fm.name) continue;

    const toml = agentToToml(fm, content);
    writeFile(
      path.join(PROJECT_ROOT, '.codex', 'agents', `${fm.name}.toml`),
      toml
    );
    console.log(`  ${file} -> .codex/agents/${fm.name}.toml`);
  }
}

function agentToToml(fm, fullContent) {
  // Extract the body after frontmatter as developer_instructions
  const normalized = fullContent.replace(/\r\n/g, '\n');
  const bodyMatch = normalized.match(/^---\n[\s\S]*?\n---\n([\s\S]*)/);
  const body = bodyMatch ? bodyMatch[1].trim() : '';

  // Truncate instructions to keep TOML manageable (Codex has its own limits)
  const instructions = body.length > 4000
    ? body.slice(0, 4000) + '\n\n[Truncated by Citadel adapter. See full definition in agents/ directory.]'
    : body;

  // Map Citadel model names to Codex model names
  const modelMap = {
    'opus':   'gpt-5.4',
    'sonnet': 'gpt-5.4-mini',
    'haiku':  'gpt-5.4-mini',
  };
  const model = modelMap[fm.model] || 'gpt-5.4';

  // Map effort to reasoning_effort
  const effortMap = {
    'high':   'high',
    'medium': 'medium',
    'low':    'low',
  };
  const effort = effortMap[fm.effort] || 'high';

  const lines = [
    '# Generated by Citadel. Do not edit manually.',
    `# Source: agents/${fm.name}.md`,
    '',
    `name = "${fm.name}"`,
    `description = "${(fm.description || '').replace(/"/g, '\\"')}"`,
    `model = "${model}"`,
    `model_reasoning_effort = "${effort}"`,
    '',
    `developer_instructions = """`,
    instructions,
    `"""`,
  ];

  return lines.join('\n') + '\n';
}

// ---- 4. Sync skills to Codex discovery path ---------------------------------

function syncSkills() {
  console.log('Syncing skills to .agents/skills/...');

  const sourceDir = path.join(CITADEL_ROOT, 'skills');
  if (!fs.existsSync(sourceDir)) {
    console.log('  No skills/ directory found, skipping.');
    return;
  }

  const targetBase = path.join(PROJECT_ROOT, '.agents', 'skills');
  const skillDirs = fs.readdirSync(sourceDir).filter(d =>
    fs.existsSync(path.join(sourceDir, d, 'SKILL.md'))
  );

  let synced = 0;
  for (const skillName of skillDirs) {
    const sourcePath = path.join(sourceDir, skillName, 'SKILL.md');
    const targetDir  = path.join(targetBase, skillName);
    const targetPath = path.join(targetDir, 'SKILL.md');

    // Copy SKILL.md
    if (!DRY_RUN) {
      ensureDir(targetDir);
      fs.copyFileSync(sourcePath, targetPath);
    }

    // Generate openai.yaml from frontmatter
    const content = fs.readFileSync(sourcePath, 'utf8');
    const fm = parseFrontmatter(content);
    if (fm.name || fm.description) {
      generateOpenAIYaml(targetDir, fm);
    }

    synced++;
  }

  console.log(`  ${synced} skills synced.`);
}

function generateOpenAIYaml(skillDir, fm) {
  const yaml = `# Generated by Citadel. Do not edit manually.
interface:
  display_name: "${(fm.name || 'unknown').replace(/"/g, '\\"')}"
  short_description: "${(fm.description || '').replace(/"/g, '\\"')}"
policy:
  allow_implicit_invocation: true
`;

  writeFile(path.join(skillDir, 'agents', 'openai.yaml'), yaml);
}

// ---- 5. Generate AGENTS.md if missing ---------------------------------------

function syncProjectGuidance() {
  console.log('Checking AGENTS.md...');

  const agentsMdPath = path.join(PROJECT_ROOT, 'AGENTS.md');
  if (fs.existsSync(agentsMdPath)) {
    console.log('  AGENTS.md already exists, skipping.');
    return;
  }

  // Try to copy from CLAUDE.md as initial content
  const claudeMdPath = path.join(PROJECT_ROOT, 'CLAUDE.md');
  if (fs.existsSync(claudeMdPath)) {
    const content = fs.readFileSync(claudeMdPath, 'utf8');
    writeFile(agentsMdPath, content);
    console.log('  Generated AGENTS.md from CLAUDE.md content.');
  } else {
    console.log('  No CLAUDE.md found. AGENTS.md will be generated by /do setup.');
  }
}

// ---- Main -------------------------------------------------------------------

function main() {
  console.log(`Citadel Codex Compatibility Generator`);
  console.log(`  Citadel root: ${CITADEL_ROOT}`);
  console.log(`  Project root: ${PROJECT_ROOT}`);
  if (DRY_RUN) console.log('  Mode: DRY RUN');
  console.log('');

  generateConfigToml();
  generatePluginManifest();
  translateAgents();
  syncSkills();
  syncProjectGuidance();

  console.log('');
  if (DRY_RUN) {
    console.log('Dry run complete. No files were written.');
  } else {
    console.log('Codex compatibility artifacts generated.');
    console.log('Run `node scripts/install-hooks-codex.js` to install Codex hooks.');
  }
}

main();
